version: '2'
services:


  mongodb:
    image: mongo:3
    volumes:
      - ./servers/mongo/data:/data/db
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    volumes:
      - ./servers/elasticsearch/data:/usr/share/elasticsearch/data
      - ./servers/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.3
    restart: always
    ports:
      - 5000:5000
      - 12205:12201
    depends_on: 
      - elasticsearch
    volumes:
      - ./servers/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./servers/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  rabbit:
    image: "rabbitmq"
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: "Dabbing"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - "./servers/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./servers/rabbitmq/mnesia:/var/lib/rabbitmq/mnesia"

  graylog:
    image: graylog/graylog:2.3.0-1
    restart: always
    environment:
      # User: admin
      # Password: admin
      - GRAYLOG_PASSWORD_SECRET=MoreGruffErNokDagensStandaRD
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://0.0.0.0:9000/api
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./servers/graylog/data:/usr/share/graylog/data/journal
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
